"""
content.py — Trigger cards and player secrets for the Alice Is Missing-inspired Telegram bot.
"""

PLAYER_SECRETS = [
    "You sent Alice threatening messages the week she disappeared.",
    "You were secretly in love with Alice and she rejected you violently.",
    "You stole $5000 from Alice and she was going to expose you.",
    "You have Alice's missing phone hidden in your apartment.",
    "You were the last person to see Alice alive at 11:47pm.",
    "Alice caught you dealing drugs and threatened to tell police.",
    "You sabotaged Alice's car brakes two days before she vanished.",
    "You have Alice's blood on your jacket from 'helping her'.",
    "Alice was pregnant with your child and wanted to keep it secret.",
    "You hacked Alice's accounts and stole her identity information.",
    "You fought with Alice over a shared lover the night she disappeared.",
    "You sold Alice fake prescription pills that made her paranoid.",
    "Alice's diary has pages torn out - you have them.",
    "You have video of Alice with someone dangerous that night.",
    "You owe Alice's family 20k from a bad business deal.",
    "You broke into Alice's apartment the day before she vanished.",
    "Alice confronted you about stalking her best friend.",
    "You have Alice's final voicemail begging for help - from you.",
    "You planted evidence to frame your rival for Alice's murder.",
    "Alice discovered your affair and was going to tell your spouse.",
    "You have the murder weapon wrapped in your gym bag.",
    "You lied about your alibi - you were with Alice when she died.",
    "Alice's pet witnessed you at the scene and hates you now.",
    "You deleted security footage that showed you near Alice's place.",
    "You have Alice's missing credit cards and made purchases.",
    "You were blackmailing Alice over her secret abortion.",
    "You poisoned Alice's drink at the party before she left.",
    "Alice's final text to you was 'I know what you did'.",
    "You have scratches on your arms from fighting Alice.",
    "You staged Alice's disappearance to collect insurance money.",
]

EARLY_TRIGGERS = [
    "Accuse the player who seems most nervous about Alice's disappearance. (Act this out publicly in your group chat)",
    "Message a player privately and hint that you saw them near Alice's house recently. (Act this out publicly in your group chat or message someone privately)",
    "Claim publicly that someone else's alibi doesn't add up. Call them out. (Act this out publicly in your group chat)",
    "Pretend you overheard a strange argument involving another player and Alice. Name them. (Act this out publicly in your group chat)",
    "Ask another player directly if they were jealous of Alice's relationships. (Act this out publicly in your group chat)",
    "Reveal that you found something suspicious in Alice's belongings that points to a specific player. (Act this out publicly in your group chat)",
    "Message someone privately about a 'dream' where they were acting strangely around Alice. (Act this out publicly in your group chat or message someone privately)",
    "Publicly question why someone was deleting messages the night Alice disappeared. (Act this out publicly in your group chat)",
    "Hint to the group that you know someone was following Alice. (Act this out publicly in your group chat)",
    "Accuse someone of lying about their relationship with Alice. (Act this out publicly in your group chat)",
    "DM a player and tell them you saw their car near the crime scene. (Act this out publicly in your group chat or message someone privately)",
    "Publicly wonder why someone never mentions their last conversation with Alice. (Act this out publicly in your group chat)",
    "Claim you have a witness who saw another player acting suspicious. (Act this out publicly in your group chat)",
    "Ask the group who benefited most from Alice disappearing. Point fingers. (Act this out publicly in your group chat)",
    "Message someone privately about their strange behavior at Alice's last party. (Act this out publicly in your group chat or message someone privately)",
    "Publicly reveal you found a clue that connects someone to Alice's phone. (Act this out publicly in your group chat)",
    "Hint that you know someone was in debt to Alice. (Act this out publicly in your group chat)",
    "Question someone's timeline from the night Alice vanished. (Act this out publicly in your group chat)",
    "Accuse someone of hiding their true feelings about Alice. (Act this out publicly in your group chat)",
    "DM a player about a 'memory' of them fighting with Alice. (Act this out publicly in your group chat or message someone privately)",
]

MID_TRIGGERS = [
    "Confront someone publicly about their suspicious phone records. (Act this out publicly in your group chat)",
    "Reveal to one player privately that you have evidence against another specific person. (Act this out publicly in your group chat or message someone privately)",
    "Publicly demand someone explain their connection to Alice's missing jewelry. (Act this out publicly in your group chat)",
    "Claim you saw security footage with someone's face blurred near Alice's place. (Act this out publicly in your group chat)",
    "Accuse two players of working together to hide something from the group. (Act this out publicly in your group chat)",
    "Message someone privately about their bloody clothes you 'found'. (Act this out publicly in your group chat or message someone privately)",
    "Publicly question why someone burned evidence the night Alice disappeared. (Act this out publicly in your group chat)",
    "Hint that Alice's diary mentioned threats from a specific player. (Act this out publicly in your group chat)",
    "DM a player confessing you saw them delete Alice's last message to them. (Act this out publicly in your group chat or message someone privately)",
    "Accuse someone of having Alice's missing key. (Act this out publicly in your group chat)",
    "Publicly reveal a hacked message that implicates another player. (Act this out publicly in your group chat)",
    "Claim someone was seen running from Alice's apartment. Name them. (Act this out publicly in your group chat)",
    "Message someone privately about their unexplained cash from Alice. (Act this out publicly in your group chat or message someone privately)",
    "Demand publicly why someone has Alice's password. (Act this out publicly in your group chat)",
    "Hint to the group about someone's restraining order against Alice. (Act this out publicly in your group chat)",
    "Accuse someone of staging Alice's disappearance for insurance. (Act this out publicly in your group chat)",
    "Reveal privately to one player that you have their fingerprints on evidence. (Act this out publicly in your group chat or message someone privately)",
    "Publicly question someone's sudden inheritance after Alice vanished. (Act this out publicly in your group chat)",
    "Claim Alice's pet reacted strangely to one specific player. (Act this out publicly in your group chat)",
    "DM someone about their fight with Alice over stolen money. (Act this out publicly in your group chat or message someone privately)",
]

LATE_TRIGGERS = [
    "Publicly declare you KNOW who the killer is. Name them. (Act this out publicly in your group chat)",
    "Reveal to everyone that you have DNA evidence against a specific player. (Act this out publicly in your group chat)",
    "Accuse someone of hiding the murder weapon. Demand they confess. (Act this out publicly in your group chat)",
    "Message every player privately with the same accusation against one person. (Act this out publicly in your group chat or message someone privately)",
    "Claim publicly that Alice's final words named her killer. (Act this out publicly in your group chat)",
    "Reveal you have a recorded confession from someone suspicious. (Act this out publicly in your group chat)",
    "Publicly demand a vote on who should be arrested immediately. (Act this out publicly in your group chat)",
    "Accuse someone of faking their own alibi with help. (Act this out publicly in your group chat)",
    "Hint that you have the killer's bloody fingerprints. (Act this out publicly in your group chat)",
    "Message one player privately: 'I know you did it. Confess or I tell everyone.' (Act this out publicly in your group chat or message someone privately)",
    "Publicly reveal Alice's safe contained evidence against one player. (Act this out publicly in your group chat)",
    "Claim you found the killer's disguise in their trash. (Act this out publicly in your group chat)",
    "Accuse someone of having an accomplice in the group. (Act this out publicly in your group chat)",
    "Reveal publicly that security cameras caught the killer's license plate. (Act this out publicly in your group chat)",
    "DM everyone: 'The killer is panicking right now.' (Act this out publicly in your group chat or message someone privately)",
    "Publicly state you have the murder timeline that proves guilt. (Act this out publicly in your group chat)",
    "Accuse someone of cleaning up the crime scene that night. (Act this out publicly in your group chat)",
    "Claim Alice's ghost is pointing at the killer. (Act this out publicly in your group chat)",
    "Reveal you have the killer's motive documented. (Act this out publicly in your group chat)",
    "Final accusation: Name the killer and give your proof. (Act this out publicly in your group chat)",
]
ORACLE_YES = [
    "Something in the stars says yes.",
    "Alice would have agreed.",
    "The signs point in your favor.",
    "You may proceed.",
    "The path ahead is clear — yes.",
    "The fates smile upon this choice.",
]

ORACLE_NO = [
    "The winds whisper no.",
    "Alice would have warned against it.",
    "The path ahead is blocked — no.",
    "Not this time, choose differently.",
    "The signs are against this choice.",
    "The fates caution you — no.",
]

SEEKING_CARDS = [

    "a bloodstained hoodie",
    "a smashed phone screen",
    "a shattered rearview mirror",
    "a dented baseball bat",
    "a muddy shovel",
    "a stained car seat cover",
    "a broken padlock",
    "a torn piece of police tape",
    "a ripped photograph",
    "a burned scrap of ID",
    "a discarded pair of latex gloves",
    "a half-empty pill bottle",
    "a wallet with the ID missing",
    "a knife sheath with no knife",
    "a roll of duct tape with strands of hair",
    "a snapped necklace chain",
    "a shoeprint stamped in dried mud",
    "a backpack with the lining cut open",
    "a hoodie with the logo scratched out",
    "a set of car keys with one key bent",
    "a gas can with a missing cap",
    "a glove smeared with something dark",
    "a bracelet caught on barbed wire",
    "a car floor mat stained and flipped over",
    "a bracelet with the name scratched off",
    "a torn page from a restraining order",
    "a hoodie string knotted too tightly",
    "a bottle of cleaner almost empty",
    "a single earring found near skid marks",
    "a car parked with its trunk slightly open",
    "a missing person flyer with the face scribbled over",
    "a burner phone with no contacts",
    "a motel key with no room number",
    "a map with one location circled in red",
    "a voice message with only breathing",
    "a social media account suddenly wiped clean",
    "a trash bag that’s too heavy for its size",
    "a pair of shoes left neatly by the roadside",
    "a diary with the last page torn out",
    "a crowbar with chipped paint",
    "a parking ticket stamped at a strange hour",
    "a USB stick with no label",
    "a hoodie left on a chair that still smells like smoke", "a rope coiled loosely on the ground",
    "a torn backpack strap lying in the dirt",
    "a cracked pair of handcuffs",
    "a broken window latch",
    "a scarf knotted too tightly around a chair",
    "a jacket sleeve with the cuff ripped off",
    "a baseball cap with dried mud on the brim",
    "a toolbox with one slot empty",
    "a crowbar with fresh scratches near the tip",
    "a shoe with the laces cut clean through",
    "a lighter engraved with unfamiliar initials",
    "a stack of photos with one missing from the middle",
    "a glove with a single fingerprint visible in dust",
    "a hotel receipt paid in cash",
    "a car seatbelt sliced almost all the way through",
    "a length of rope frayed at both ends",
    "a hoodie with the inside pocket carefully removed",
    "a bottle labeled as cleaner but smelling like gasoline",
    "a metal pipe hidden behind a trash bin",
]

GROUP_REMINDERS = [
    (90, "⏳ The first card awaits… unfold it now."),
    (80, "🕯 A secret stirs. Reveal your next card."),
    (70, "📜 Another clue emerges — check your card."),
    (60, "🌙 Shadows shift. Uncover the next card."),
    (50, "🔎 A detail comes into focus. Reveal your card."),
    (45, "✨ Something unexpected awaits — unfold your card."),
    (40, "⚡ The tension rises. Check your next clue."),
    (35, "🕰 Time moves on… another card is ready."),
    (30, "🔍 A key hint appears. Reveal it now."),
    (20, "🌟 The end is nearing. Check your card carefully."),
    (10, "⚡ Times up! Unfold your final clue before the story ends."),
]
